theme: minima
title: My Blog Journey
author: Smith Thay
email: contact.smith.thay@gmail.com
description: > # this means to ignore newlines until "baseurl:"


github_username:  github.com/smiththay

show_excerpts: true # set to false to remove excerpts on the homepage
